---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Download Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/debian"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
    enabled: true

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install Containerd
  become: true
  ansible.builtin.apt:
    name: containerd.io
    state: present
