---
kube_scheduler_version: 1.35.0
kube_scheduler_checksum:
kube_scheduler_mode: staticpod
kube_scheduler_installation_dir: /usr/local/kubernetes
kube_scheduler_static_pod_dir: /etc/kubernetes/manifests
kube_scheduler_pki_dir: /etc/kubernetes/pki
kube_scheduler_ca_cert_content:
kube_scheduler_ca_key_content:
