---
apiVersion: v1
kind: Secret
metadata:
  name: internal-ca
  namespace: cert-manager
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    << content of the cert >>
    -----END CERTIFICATE-----

