---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-root
  namespace: cert-manager
  labels:
    app.kubernetes.io/managed-by: kubectl
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
type: Opaque
data:
  tls.crt: >
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuakNDQVVXZ0F3SUJBZ0lRSlFYekJ5cmdw
    clA5Wmk1bHM4T3VzekFLQmdncWhrak9QUVFEQWpBdU1SRXcKRHdZRFZRUUtFd2hJYjIxbElGQkxT
    VEVaTUJjR0ExVUVBeE1RU0c5dFpTQlFTMGtnVW05dmRDQkRRVEFlRncweQpOakE0TURZd016TXdN
    RGRhRncwek5qQTRNRE13TXpNd01EZGFNQzR4RVRBUEJnTlZCQW9UQ0VodmJXVWdVRXRKCk1Sa3dG
    d1lEVlFRREV4QkliMjFsSUZCTFNTQlNiMjkwSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpq
    MEQKQVFjRFFnQUU0cWJiZERUcE5YMENteFVWYU4veVFxRkw1UVMyb2hEVmg0bk8yUDc1OXI0anlI
    RHh6UEZCYUphTQp3SnNLaEZ3WWNxYTJBUElFZ1Z3MU5DUWFNM2xkLzZORk1FTXdEZ1lEVlIwUEFR
    SC9CQVFEQWdFR01CSUdBMVVkCkV3RUIvd1FJTUFZQkFmOENBUUV3SFFZRFZSME9CQllFRkplQTdr
    cTJRYlJucGRtLzJHNWE5UGNQR0t2OU1Bb0cKQ0NxR1NNNDlCQU1DQTBjQU1FUUNJR2FXRDBCbUZO
    Vjh1aVdZcnZnU0xtWlhIcXdiSW03Tmg3TE93Y09LeWVDVQpBaUFzZVhxQ3NqY25DdllzakU5MWZu
    SFZtU2F2QkllRWd2QzR1U0VKbCtmNHlBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=


