# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: proxmox-csi-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        config.yaml: |
          clusters:
            - url: https://proxmox.u74n.internal:8006/api2/json
              insecure: false
              token_id:  kubernetes-csi@pve!proxmox-csi
              token_secret: "{{ .tokenSecret }}"
              region: Region-1
  data:
    - remoteRef:
        key: /home/proxmox/csi/token_secret
      secretKey: tokenSecret

