---
existingConfigSecret: proxmox-csi-config

# Define Proxmox storage class
storageClass:
  - name: proxmox-csi-xfs
    storage: local-lvm
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    fstype: xfs
    cache: none
    ssd: true
    mountOptions:
      - discard


