---
argument_specs:
  main:
    description: Install and configure Kubectl
    short_description: Install and configure Kubectl
    author:
      - U74n
    options:
      # Version
      kubernetes_version:
        type: str 
        description:
          - "Kubernetes version to install Kubectl"
        required: true

      # PKI 
      kubernetes_ca_cert_content:
        type: str 
        description:
          - "Kubernetes CA certificate content"
          - "Default: if not provided, It will slurp the CA certificate from CA server"
        required: false

      kubernetes_ca_key_content:
        type: str 
        description:
          - "Kubernetes CA private key content"
          - "Default: if not provided, It will slurp the CA private key from CA server"
        required: false

      kubernetes_ca_server:
        type: str 
        required: false 
        default: "{{ groups['control_plane'] | sort | first }}"

      kubernetes_remote_ca_cert_path:
        type: path 
        description:
          - "Remote path of Kubernetes CA certificate on the CA server"
          - "Default: /etc/kubernetes/pki/ca.crt"
        required: false
        default: /etc/kubernetes/pki/ca.crt
      
      kubernetes_remote_ca_key_path:
        type: path 
        description:
          - "Remote path of Kubernetes CA private key on the CA server"
          - "Default: /etc/kubernetes/pki/ca.key"
        required: false
        default: /etc/kubernetes/pki/ca.key

      kubeconfig_not_after:
        type: str 
        description:
          - "Default: 10 years from now"
        required: false
        default: ""
  
  kubeconfig:
    description: Generate kubeconfig file for cluster access
    short_description: Generate kubeconfig file for cluster access
    author:
      - U74n
    options:
      # Version
      kubernetes_version:
        type: str 
        description:
          - "Kubernetes version to install Kubectl"
        required: true

      # PKI 
      kubernetes_ca_cert_content:
        type: str 
        description:
          - "Kubernetes CA certificate content"
          - "Default: if not provided, It will slurp the CA certificate from CA server"
        required: false

      kubernetes_ca_key_content:
        type: str 
        description:
          - "Kubernetes CA private key content"
          - "Default: if not provided, It will slurp the CA private key from CA server"
        required: false

      kubernetes_ca_server:
        type: str 
        required: false 
        default: "{{ groups['control_plane'] | sort | first }}"

      kubernetes_remote_ca_cert_path:
        type: path 
        description:
          - "Remote path of Kubernetes CA certificate on the CA server"
          - "Default: /etc/kubernetes/pki/ca.crt"
        required: false
        default: /etc/kubernetes/pki/ca.crt
      
      kubernetes_remote_ca_key_path:
        type: path 
        description:
          - "Remote path of Kubernetes CA private key on the CA server"
          - "Default: /etc/kubernetes/pki/ca.key"
        required: false
        default: /etc/kubernetes/pki/ca.key

      kubeconfig_not_after:
        type: str 
        description:
          - "Default: 10 years from now"
        required: false
        default: ""



      
