---
- name: Download K3s Binaries
  ansible.builtin.get_url:
    url: "https://get.k3s.io"
    dest: /tmp/k3s_install.sh
    mode: "0755"

- name: Install K3s
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: "true"
    K3S_KUBECONFIG_MODE: "644"
  ansible.builtin.shell: |
    /tmp/k3s_install.sh agent \
      --server https://{{ k3s_server_address }}:6443 \
      --token {{ k3s_token }}
  args:
    creates: /usr/local/bin/k3s
