# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    cnpg.io/reconciliationLoop: enabled
spec:
  instances: 1
  storage:
    size: 50Gi
    storageClass: proxmox-csi-xfs
    resizeInUseVolumes: true
  managed:
    roles:
      # Role for Gitea to connect to database
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: gitea
        superuser: false
        login: true
        passwordSecret:
          name: gitea-db-cred


