---
- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_repo_url: https://helm.cilium.io/
    kubeconfig: "{{ kubeconfig }}"
    namespace: kube-system
    create_namespace: false
    values: "{{ _cilium_values }}"


