# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/trust.cert-manager.io/bundle_v1alpha1.json
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: internal-ca
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  sources:
    - secret:
        name: step-ca-root
        key: tls.crt

  target:
    configMap:
      key: internal-ca.crt
      metadata:
        labels:
          app.kubernetes.io/component: trust-bundler

