---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Etcd
  become: true
  when: _mode == "systemd"
  ansible.builtin.systemd:
    name: etcd
    state: restarted
