# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  sources:
    - repoURL: https://gitea.k8s.u74n.internal/utan/home.git
      targetRevision: main
      ref: src

    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $src/k8s/platform/networking/cilium/values.yaml

    - repoURL: https://gitea.k8s.u74n.internal/utan/home.git
      targetRevision: main
      path: k8s/platform/networking/cilium

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
