# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/cert-manager.io/certificate_v1.json
---
apiVersion: cert-manager.io/v1
kind: Certficate
metadata:
  name: wildcard-u74n-internal
spec:
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: wildcard-u74n-tls-cert
  dnsNames:
    - "*.u74n.internal"
    - "u74n.internal"
