rbac:
  create: false

serviceAccount:
  create: false

replicas: 1

readinessProbe:
  httpGet:
    path: /api/health
    port: grafana

livenessProbe:
  httpGet:
    path: /api/health
    port: grafana
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

resources:
  requests:
    cpu: 250m
    memory: 750Mi
  limits:
    memory: 1.5Gi

env:
  - name: GF_DATABASE_TYPE
    value: postgres
  - name: GF_DATABASE_HOST
    value: postgresql-cluster-rw.cnpg.svc.cluster.local:5432
  - name: GF_DATABASE_NAME
    value: grafana
  - name: GF_DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: grafana-db-cred
        key: username
  - name: GF_DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: grafana-db-cred
        key: password

service:
  enabled: true
  tyoe: ClusterIP

ingress:
  enabled: false

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: cilium-gw
        namespace: gateway
        sectionName: https
    hostnames:
      - grafana.k8s.u74n.internal

plugins:
  - grafana-clock-panel
  - grafana-piechart-panel



