---
name: Pull Request CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  changes:
    name: Register changes
    runs-on: infra
    outputs:
      infrastructure: ${{ steps.filters.outputs.infrastructure }}
      configuration: ${{ steps.filters.outputs.configuration }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v4

      - name: Register changes
        id: filters
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: ".gitea/ci-filter.yaml"

  terraform-dry-run:
    name: Terraform Dry Run
    runs-on: infra
    needs: changes
    if: needs.changes.outputs.infrastructure == 'true'
    outputs:
      terraform_dry_run: ${{ steps.terraform_dry_run.outputs.terraform_dry_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v4

      - name: Terraform Dry Run
        id: terraform_dry_run
        run: echo "terraform_dry_run=Terraform dry run result" >> $GITHUB_OUTPUT

  ansible-dry-run:
    name: Ansible Dry Run
    runs-on: infra
    needs: changes
    if: needs.changes.outputs.configuration == 'true'
    outputs:
      ansible_dry_run: ${{ steps.ansible_dry_run.outputs.ansible_dry_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v4

      - name: Ansible Dry Run
        id: ansible_dry_run
        run: echo "ansible_dry_run=Ansible dry run result" >> $GITHUB_OUTPUT

  report:
    name: PR Report
    runs-on: infra
    needs:
      - terraform-dry-run
      - ansible-dry-run
    if: always()
    steps:
      - name: Comment on PR
        env:
          GITEA_SERVER_URL: http://gitea_server:3000
          GITEA_SERVER_TOKEN: ${{ secrets.TOKEN }}
          REPO: utan/home
          PR_NUMBER: ${{ gitea.event.pull_request.number }}
          TERRAFORM_RESULT: ${{ needs.terraform-dry-run.outputs.terraform_dry_run }}
          ANSIBLE_RESULT: ${{ needs.ansible-dry-run.outputs.ansible_dry_run }}
        run: |
          sudo apt-get update 
          sudo apt-get install -y tea-cli

          tea-cli logins add \
            --name gitea \
            --url "$GITEA_SERVER_URL" \
            --token "$GITEA_SERVER_TOKEN"

          echo "Targeting Repo: $REPO"
          echo "Targeting PR: $PR_NUMBER"

          if [[ ! -z "$TERRAFORM_RESULT" ]]; then
            tea-cli pr comment "$PR_NUMBER" \
              --login gitea \
              --repo $REPO \
              --body "$TERRAFORM_RESULT"
          fi 

          if [[ ! -z "$ANSIBLE_RESULT" ]]; then
            tea-cli pr comment "$PR_NUMBER" \
              --login gitea \
              --repo $REPO \
              --body "$ANSIBLE_RESULT"
          fi
