---
global:
  domain: argocd.k8s.u74n.internal
  logging:
    format: text
    level: info

configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-helm
  tls:
    certificates:
      gitea.k8s.u74n.internal: |
        -----BEGIN CERTIFICATE-----
        MIIBnjCCAUWgAwIBAgIQJQXzByrgprP9Zi5ls8OuszAKBggqhkjOPQQDAjAuMREw
        DwYDVQQKEwhIb21lIFBLSTEZMBcGA1UEAxMQSG9tZSBQS0kgUm9vdCBDQTAeFw0y
        NjA4MDYwMzMwMDdaFw0zNjA4MDMwMzMwMDdaMC4xETAPBgNVBAoTCEhvbWUgUEtJ
        MRkwFwYDVQQDExBIb21lIFBLSSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAE4qbbdDTpNX0CmxUVaN/yQqFL5QS2ohDVh4nO2P759r4jyHDxzPFBaJaM
        wJsKhFwYcqa2APIEgVw1NCQaM3ld/6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1Ud
        EwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFJeA7kq2QbRnpdm/2G5a9PcPGKv9MAoG
        CCqGSM49BAMCA0cAMEQCIGaWD0BmFNV8uiWYrvgSLmZXHqwbIm7Nh7LOwcOKyeCU
        AiAseXqCsjcnCvYsjE91fnHVmSavBIeEgvC4uSEJl+f4yA==
        -----END CERTIFICATE-----

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

server:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  service:
    type: ClusterIP
  httproute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: cilium-gw
        namespace: gateway
        sectionName: https

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# cache
redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false
