---
# Stop other mode deployments
- name: Stop Kube-controller-manager systemd deployment
  become: true 
  when:
    - _mode != "systemd"
    - "'kube-controller-manager.service' in ansible_facts.services"
    - ansible_facts.services['kube-controller-manager.service']['state'] in ['running', 'active']
  ansible.builtin.systemd:
    name: kube-controller-manager 
    state: stopped

- name: Stop Kube-controller-manager static pod deployment 
  become: true
  when:
    - _mode != "staticpod"
  ansible.builtin.file:
    name: "{{ kubernetes_static_pod_dir }}/controller-manager.yaml"
    state: absent

# Start the deployment for the selected mode
- name: Start Kube-controller-manager systemd deployment
  become: true 
  when: _mode == "systemd"
  ansible.builtin.systemd:
    name: kube-controller-manager 
    state: started
    enabled: true

- name: Start Kube-controller-manager static pod deployment 
  become: true
  when: _mode == "staticpod"
  ansible.builtin.template:
    src: controller-manager.yaml.jinja
    dest: "{{ kubernetes_static_pod_dir }}/controller-manager.yaml"
    owner: root
    group: root
    mode: "0644"
