---
- name: Write CAs
  become: true
  no_log: true
  loop_control:
    loop_var: ca_item
  loop:
    - dest: "{{ kube_controller_manager_pki_dir }}/ca.crt"
      content: "{{ kube_controller_manager_ca_cert_content }}"
      mode: '0644'
    - dest: "{{ kube_controller_manager_pki_dir }}/ca.key"
      content: "{{ kube_controller_manager_ca_key_content }}"
      mode: '0600'
  ansible.builtin.copy:
    dest: "{{ ca_item.dest }}"
    content: "{{ ca_item.content }}"
    owner: root
    group: root
    mode: "{{ ca_item.mode }}"

- name: Generate Kube-controller-manager key
  become: true
  register: _kube_controller_manager_privkey
  community.crypto.openssl_privatekey:
    path: "{{ kube_controller_manager_pki_dir }}/controller-manager.key"
    size: 2048

- name: Generate CSR for Kube-controller-manager
  become: true
  register: _kube_controller_manager_csr
  changed_when: _kube_controller_manager_privkey.changed
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ kube_controller_manager_pki_dir }}/controller-manager.key"
    common_name: system:kube-controller-manager

- name: Sign Kube-controller-manager certificate
  become: true
  community.crypto.x509_certificate:
    path: "{{ kube_controller_manager_pki_dir }}/controller-manager.crt"
    csr_content: "{{ _kube_controller_manager_csr.csr }}"
    provider: ownca
    ownca_content: "{{ kube_controller_manager_ca_cert_content }}"
    ownca_privatekey_content: "{{ kube_controller_manager_ca_key_content }}"
