---
- name: Turn off swap
  when: kubelet_swap_check.stdout != ''
  become: true
  changed_when: false
  ansible.builtin.command:
    cmd: swapoff -a

- name: Remove swap entry in fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: "^([^#].*swap.*)$"
    replace: '# \1'
