---
- name: Slurp scheduler key
  become: true
  register: _kube_scheduler_key
  ansible.builtin.slurp:
    src: "{{ kube_scheduler_pki_dir }}/scheduler.key"

- name: Slurp scheduler certificate
  become: true
  register: _kube_scheduler_cert
  ansible.builtin.slurp:
    src: "{{ kube_scheduler_pki_dir }}/scheduler.crt"

- name: Write scheduler kubeconfig
  become: true
  notify:
    - Restart Kube-scheduler
  ansible.builtin.template:
    src: scheduler.conf.jinja
    dest: /etc/kubernetes/scheduler.conf
    owner: root
    group: root
    mode: "0600"

- name: Copy service template
  become: true
  when: kube_scheduler_mode == "systemd"
  notify:
    - Reload systemd
    - Restart Kube-scheduler
  ansible.builtin.template:
    src: scheduler.service.jinja
    dest: /etc/systemd/system/kube-scheduler.service
    owner: root
    group: root
    mode: "0644"
