---
- name: Ensure Kubernetes directory
  become: true
  loop_control:
    loop_var: kubernetes_dir
  loop:
    - "{{ kube_scheduler_installation_dir if kube_scheduler_mode == 'systemd' else omit }}"
    - "{{ kube_scheduler_pki_dir }}"
    - "{{ kube_scheduler_static_pod_dir if kube_scheduler_mode == 'staticpod' else omit }}"
  ansible.builtin.file:
    path: "{{ kubernetes_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Kube-scheduler binary
  become: true
  when: kube_scheduler_mode == "systemd"
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/v{{ kube_scheduler_version }}/bin/linux/amd64/kube-scheduler"
    dest: "{{ kube_scheduler_installation_dir }}/kube-scheduler-{{ kube_scheduler_version }}"
    checksum: "sha256:{{ kube_scheduler_checksum }}"
    owner: root
    group: root
    mode: "0755"

- name: Symlink Kube-scheduler binary
  become: true
  when: kube_scheduler_mode == "systemd"
  notify:
    - Restart Kube-scheduler
  ansible.builtin.file:
    src: "{{ kube_scheduler_installation_dir }}/kube-scheduler-{{ kube_scheduler_version }}"
    dest: /usr/local/bin/kube-scheduler
    state: link
