---
- name: Preflight check
  ansible.builtin.import_tasks: preflight.yaml

- name: Install
  ansible.builtin.import_tasks: install.yaml

- name: Configure PKI
  ansible.builtin.import_tasks: pki.yaml

- name: Configure
  ansible.builtin.import_tasks: configure.yaml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Deploy 
  ansible.builtin.import_tasks: deploy.yaml
