---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _kube_scheduler_dependencies }}"
    state: present

# Set Kubernetes CA key, if not found create one at the first control plane
- name: Set Kubernetes CA key
  when: kube_scheduler_ca_key_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_key.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: "{{ kube_scheduler_pki_dir }}/ca.key"
    variable: kube_scheduler_ca_key_content

# Set Kubernetes CA certificate, if not found create one at the first control plane
- name: Set Kubernetes CA certificate
  when: kube_scheduler_ca_cert_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_cert.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: "{{ kube_scheduler_pki_dir }}/ca.crt"
    variable: kube_scheduler_ca_cert_content
    ca_key_content: "{{ kube_scheduler_ca_key_content }}"
    ca_common_name: Kubernetes CA

# Fetch Kube-scheduler checksum
- name: Fetch Kube-scheduler checksum
  when:
    - kube_scheduler_mode == "systemd"
    - not kube_scheduler_checksum
  block:
    - name: Get Kube-scheduler checksum
      changed_when: false
      register: _kube_scheduler_checksum_result
      ansible.builtin.uri:
        url: "https://dl.k8s.io/v{{ kube_scheduler_version }}/bin/linux/amd64/kube-scheduler.sha256"
        return_content: true

    - name: Set Kube-scheduler checksum fact
      ansible.builtin.set_fact:
        kube_scheduler_checksum: "{{ _kube_scheduler_checksum_result.content }}"

# Gather service facts
- name: Gather service facts
  become: true
  ansible.builtin.service_facts:

# Ensure kube_scheduler_installation_dir is correctly set
- name: Assert kube_scheduler_installation_dir is correctly set
  when:
    - kube_scheduler_mode == 'systemd'
    - _kube_scheduler_is_installation_dir_blank
  ansible.builtin.fail:
    msg: "kube_scheduler_installation_dir is required when deployment mode is systemd."

# Ensure kube_scheduler_static_pod_dir is correctly set
- name: Assert kube_scheduler_static_pod_dir is correctly set
  when:
    - kube_scheduler_mode == 'staticpod'
    - _kube_scheduler_is_static_pod_dir_blank
  ansible.builtin.fail:
    msg: "kube_scheduler_static_pod_dir is required when deployment mode is staticpod."
