---
- name: Configure Control Plane
  hosts: control_plane
  serial: 1
  gather_facts: false
  tasks:
    - name: Wait for SSH
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300
        delay: 10

    - name: Gather facts
      ansible.builtin.gather_facts:

    - name: Preconfigure virtual machine
      ansible.builtin.import_role:
        name: vm

    - name: Containerd
      ansible.builtin.import_role:
        name: containerd

    - name: Kubeadm
      ansible.builtin.import_role:
        name: kubeadm

    - name: Kubelet
      ansible.builtin.import_role:
        name: kubelet

    - name: Flush handler
      ansible.builtin.meta: flush_handlers

    # TODO: when configure HA cluster, swapout the ip to a HA Proxy
    # If not, then all cluster will only listen to the first control plane node, ultimately become the single point of failure
    - name: Check if the cluster is initialized
      register: cluster_health
      until: cluster_health.status == 200
      retries: 3
      delay: 10
      failed_when: false
      ansible.builtin.uri:
        url: https://{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}:6443/healthz
        validate_certs: false

    - name: Initialize the cluster
      when: cluster_health.status != 200
      block:
        - name: Kubeadm init
          ansible.builtin.include_role:
            name: kubeadm
            tasks_from: init

        - name: Ensure kubeconfig directory exists
          ansible.builtin.file:
            path: "{{ ansible_facts['env']['HOME'] }}/.kube"
            state: directory

        - name: Configure kubeconfig
          become: true
          ansible.builtin.copy:
            remote_src: true
            src: /etc/kubernetes/admin.conf
            dest: "{{ ansible_facts['env']['HOME'] }}/.kube/config"
            mode: "0600"
            owner: "{{ ansible_facts['env']['USER'] }}"
            group: "{{ ansible_facts['env']['USER'] }}"

        - name: Helm
          ansible.builtin.include_role:
            name: helm

        - name: Install CNI
          kubernetes.core.helm:
            name: cilium
            chart_ref: cilium
            chart_repo_url: https://helm.cilium.io/
            namespace: kube-system
            create_namespace: false
            values:
              kubeProxyReplacement: "true"
              socketLB:
                hostNamespaceOnly: "true"

        - name: Set join command fact
          register: join_command
          become: true
          ansible.builtin.command: kubeadm token create --print-join-command

    - name: Join the cluster
      when: cluster_health.status == 200
      block:
        - name: Get join command from control plane
          register: join_command
          become: true
          ansible.builtin.command: kubeadm token create --print-join-command
          delegate_to: "{{ groups['control_plane'][0] }}"

        - name: Set join command fact
          ansible.builtin.set_fact:
            join_command: "{{ join_command.stdout }}"

        - name: Join the cluster
          ansible.builtin.include_role:
            name: kubeadm
            tasks_from: join
