---
- name: Configure Control Plane
  hosts: control_plane
  serial: 1
  pre_tasks:
    - name: Configure DNS
      become: true
      ansible.builtin.blockinfile:
        path: /etc/resolv.conf
        block: |
          nameserver 1.1.1.1
          nameserver 8.8.8.8
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DNS CONFIGURATION"

    - name: Update apt cache (Debian)
      when: ansible_facts['os_family'] == "Debian"
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Update dnf cache (RedHat)
      when: ansible_facts['os_family'] == "RedHat"
      become: true
      ansible.builtin.dnf:
        update_cache: true

    - name: Update AUR cache (ArchLinux)
      when: ansible_facts['os_family'] == 'ArchLinux'
      community.general.pacman:
        update_cache: true

    - name: Ensure dependencies
      become: true
      ansible.builtin.package:
        name:
          - python3-cryptography
        state: present

    - name: Enable IPv4 forwarding for Containerd
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: true

    - name: Check swap
      become: true
      ansible.builtin.command: swapon --show
      register: kubelet_swap_check
      changed_when: false
      failed_when: false

    - name: Turn off swap
      when: kubelet_swap_check.stdout != ''
      become: true
      block:
        - name: Turn off swap temporarily
          ansible.builtin.command:
            cmd: swapoff -a

        - name: Turn off swap permanently
          ansible.builtin.replace:
            path: /etc/fstab 
            regexp: "^([^#].*swap.*)$"
            replace: '# \1'

    - name: Disable swap for Kubelet
      become: true
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: "^([^#].*swap.*)$"
        replace: '# \1'
  tasks:
    - name: Generate Etcd CA 
      ansible.builtin.import_role:
        name: certificate-authority
      vars:
        ca_key_path: /etc/etcd/pki/ca.key 
        ca_cert_path: /etc/etcd/pki/ca.crt 
        ca_common_name: Etcd CA

    - name: Generate Kubernetes CA 
      ansible.builtin.import_role:
        name: certificate-authority
      vars:
        ca_key_path: /etc/kubernetes/pki/ca.key 
        ca_cert_path: /etc/kubernetes/pki/ca.crt 
        ca_common_name: Kubernetes CA

    - name: Etcd
      ansible.builtin.import_role:
        name: etcd
      vars:
        etcd_advertise_server_address: "{{ ansible_facts['default_ipv4']['address'] }}"
        etcd_advertise_peer_address: "{{ ansible_facts['default_ipv4']['address'] }}"

    - name: Kube-apiserver
      ansible.builtin.import_role:
        name: kube-apiserver

    - name: Kube-controller-manager
      ansible.builtin.import_role:
        name: kube-controller-manager

    - name: Kube-scheduler
      ansible.builtin.import_role:
        name: kube-scheduler

    - name: Containerd
      ansible.builtin.import_role:
        name: containerd

    - name: Kubelet
      ansible.builtin.import_role:
        name: kubelet


