---
- name: Configure Control Plane
  hosts: control_plane
  tasks:
    - name: Preconfigure virtual machine
      ansible.builtin.import_role:
        name: vm

    - name: Containerd
      ansible.builtin.import_role:
        name: containerd

    - name: Kubeadm
      ansible.builtin.import_role:
        name: kubeadm

    - name: Kubelet
      ansible.builtin.import_role:
        name: kubelet
