---
- name: Configure Gitea on the server
  hosts: gitea
  tasks:
    - name: Install Tailscale
      ansible.builtin.import_role:
        name: tailscale

    - name: Install Nginx
      ansible.builtin.import_role:
        name: nginx

    - name: Install Docker
      ansible.builtin.import_role:
        name: docker

    - name: Install PostgreSQL
      ansible.builtin.import_role:
        name: postgresql
      vars:
        postgresql_tag: 15

    - name: Install Gitea
      ansible.builtin.import_role:
        name: gitea
      vars:
        gitea_tag: 1.25.5-rootless

    - name: Install Gitea Runner
      ansible.builtin.import_role:
        name: gitea-runner
      vars:
        gitea_runner_tag: latest
