---
- name: Configure Worker Nodes
  hosts: worker
  gather_facts: false
  tasks:
    - name: Wait for SSH
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300
        delay: 10

    - name: Gather facts
      ansible.builtin.gather_facts:

    - name: Preconfigure virtual machine
      ansible.builtin.import_role:
        name: vm

    - name: Longhorn prerequisites
      ansible.builtin.import_role:
        name: longhorn

    - name: Containerd
      ansible.builtin.import_role:
        name: containerd

    - name: Kubeadm
      ansible.builtin.import_role:
        name: kubeadm

    - name: Kubelet
      ansible.builtin.import_role:
        name: kubelet

    - name: Flush handler
      ansible.builtin.meta: flush_handlers

    # TODO: when configure HA cluster, swapout the ip to a HA Proxy
    # If not, then all cluster will only listen to the first control plane node, ultimately become the single point of failure
    - name: Check if the cluster is initialized
      register: cluster_health
      until: cluster_health.status == 200
      retries: 3
      delay: 10
      failed_when: false
      ansible.builtin.uri:
        url: https://{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}:6443/healthz
        validate_certs: false

    - name: Join the cluster
      when: cluster_health.status == 200
      block:
        - name: Get join command from control plane
          register: join_command
          when: join_command is not defined
          become: true
          ansible.builtin.command: kubeadm token create --print-join-command
          delegate_to: "{{ groups['control_plane'][0] }}"

        - name: Join the cluster
          ansible.builtin.include_role:
            name: kubeadm
            tasks_from: join
