apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: tekton-operator
spec:
  targetNamespace: tekton
  profile: all

  dashboard:
    readonly: true
    options:
      disabled: false
      configMaps: {}
      deployments: {}
      webhookConfigurationOptions: {}

  platforms:
    kubernetes:
      pipelinesAsCode:
        options:
          deployments:
            pipelines-as-code-controller:
              metadata:
                labels:
                  internal-ca: "true"



