---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: infra
spec:
  encryptedData:
    password: AgCRwTixM3Z/Fn7Ck+InItmwp7koN/rgrvIxJ/7gUZjbtTpWV9R3lo+oLTOQTj3xumC9/KVIZ0dWg7SQmg2ZkJ1gPOorTO9k3FfHy6VaGyzZz0YnVRY6NPnPhmSCQpXkYG5ACqyKBk1Gr3AYCwek4mGJBCUKYBiV93lOR0oQ3jZedHxKM1+zF6G5NoZp/bofmao3FDW34QHPXFSYwCSLqZcJ+2sX1NKAaEuGIRoRrQ4gNaGmH1Deozcb0V9Z+exs7UsB4/xDrBNcxnV8JUblHjRg16zFiz85iybjS9mbbzKy8Hl0jPCv7Q9R/ssuFCeuqmlmMfDLaWqeMNz70f3ZVjax8swYtq06tbjvizR/pIfykfAtayUT/CyMg/f3lAMbL4/URKgGQG0Y5VxkFRhtiYI7NAUSZpB8t6zoHakzbWjBFNN5rnX8a/a346mupjep5aZotDbjdM6467wbKBVqOnvbgNCws7LZ0MJu4xugG4aXR8sZn1GLH9IU55MBmZO4UisIKfmgXr4V0JYUVJqOFJFWr1MA6N/JGmm6F4ANIttvw/GVp+WJVnAA8OypdkjD4J+RGU3dkZj7YJwAv1iwFR4ibKMXkAx0u76FEX2ARg5nYYf539T7aalo3p1iKaCrOAK8iExISwgrloOwYFDKWxxc73+4k61dNWu/3uZI+vhkwJO90RoB3/U7SG8tdWgvFa39dZ5YXZs=
    username: AgBKIGdWhwsLxyfhycb5CN1KzkgBsGBpFspTroOPNPBg+5xelCdmPh6/JPumftdz6j7RDFs8co6fdMqbaVikQ9eG+GGn4Z4P+m3kJAIJt/ganBU/+08JvU/lIS1l26fUjxNiT0wrzk5Kye7w/YzOwfuaAUja3FOZyndalJ0sCs5OY5M6cENMOkAUZ2J/6446Il02Pi5/OBcVEBEnUDMJIWdM+OJkZu4yRleij9gX2JPcvwHA4+SrWlryEgT3xU0DAAzuyZVlkCwe7eRHAYSggaCzoK8KiLOAnEN+h1sZ7PJRGfQ3GFCVHjcydys0kBWl7PjKkdjJ0heLdAJfrlfHABMUxc8bXWIzdV64HkUARD2uizEmPCcJAkoa8lxP+tFASSPy/gIdkecFac2qa+8wOzTb3N4Mom2KGyI50YOEAxx8EDlrXYz3hLT4S5Bq5fT3sqDlAUbQT7DqM8fjfQyW+Wc+LgAoJFIELIpk/g0IpgMqiKVEf4YbljjD0N/TRe2aOzsbRXFWEkZvww/3M+lktnafE52ZYrgfUjIJSreY9zknj3x5cxFApPMW+X3yApjugyPIWi7NsuQU37rq4a1W57usQuW5oPc0ZrIIWf1rX9KrntZWi9xk3Yb2oQ7u/LL1pPA/SvcIY+jyvQC6q2cRgkYODTzc7qNtUXVkCwtPVSsTwFWcmQrmX9ttLh7FtxiDw87ag+7pxJ0SyQ==
  template:
    metadata:
      name: postgres-auth
      namespace: infra
    type: Opaque
