---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: infra
spec:
  encryptedData:
    password: AgCTwsJYecY8knVuXBsbgRXRQriu+htaJpiWtR/qDlEUuvplPf3cmVydUTWrypuIrm7l0VIJayu4UsDJcR390J27e/w8Yn3qTK7OlrKz1PzsGnNrGJnvdhkuoVvvALTcnXXjLqqTL4TXnlwfrtVG9Pw7lKYTsh4S3SmjvWy4MjT6V9BZOGVUaBO/C+KvBT3i7dY20+2mm3oVOPMlLaI5j/VcJF2vl7xHtPHvaTXxuvwYfBX3J1O5/5ULOLdh+fvvcdwgMkcUZsVEdDSk2KpbFPcMGOwCxyoNchHixRSu2BNtSJNqhKl2t+Cjz4ml7kQYZ+TKANXeKbipzVX7ZU1zcYYPFx1ltxqNTK4wg2VN16Jknl0cEJvVOf3dMpog+kKbOfGSYoXacBZh6DElgSzmElgb4rvZZYbzw9aT/84I6X1DJ1aRd5GrG9hBLJjfRU6F1FpZgwG3jFOgAFWjY4R8vyN7MDHfvjUuat/BvEJNfPGpd34eSwbvrUfxK8ENJYYGJ7umLFUuthGknqDPlxdQK1quznF5oEL7POSfxLbPdg6a+3b5+W0Bc3gC7BujqPx98+CADuQCd1VUXmyD/nFgzfwDaJYJEEkrHjNm9gVaJhcmdXKAAD8TJmQmkOvvqghj//L+VqPIQVxYxDko6d9T7qZf+xlRTRaa2mpMzqcZ8hdxDXi8maXfNdE6Ld6eOJ7PKtaJoKrmavQ=
    username: AgBWao75TPjtRn5HtOA9N+Gtx6x+1jqTSNSmxnJ3F89Ycl5b/JCRKTBPPEfmNv6oIVizx2SI0uc4snAUIpYePVBLEfeWTeV0a7XTEMo3PEq7Mpkt3+Pgq4d1HYd2rWx5bPjj3ghGjijN/0rXJQIncQATuH5hoZ4IJJjOuOh6OIL0eH4vRadcK0SRTbLkMkKbr3j/j5R2fIy7eUIcJIpgK/dCpIz1ntW9/jrSYPpqx+IlG5jYOSKR+oDzI5ftsmLcUfPRf4tEsrnxdHn3qmjb5b1ZQaz4dnCc8XyV77KZZjj3hgclt/wpUZ+gsAI0xOjPDQjGnI3tDcR6y+lqxV398T3AAXiETfB/qPiUq5q5DfflAKEWUvRJkgLfcdevc89HBTAdQuS5yfF7I3416LojDiTL7m+Vf2znYtiFS8NPxKloOR3TZ5QyBfEgO5ucEXfiEoSG3fIjMMaOd37t6r7aXRT8kviYU9s2HFpXvCasKVMhBrcOx3nwOBPIIVhmZa/JP+JhXvSDh/FNUfs6jd/cCVfuy353nRmQHoBtrnF5vbLh9XI8OA7eQSXr68WV+h6YbeU+7QQlT3wFKftoO9yCrBaBTDEZqgCnV1clQLwXyALuvuUtDMCtBkGo/C/V3aEUr01EPkGwv3c65VDoOPgpkgCV7gtmO7GLRUvM9akPoiLnumxs7SBJB581QmfG3DIeW9dlz+EZYWlMMQ==
  template:
    metadata:
      name: postgres-secret
      namespace: infra
    type: Opaque
