---
apiVersion: policies.kyverno.io/v1alpha1
kind: GeneratingPolicy
metadata:
  name: apply-network-policy
spec:
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - namespaces
  variables:
    - name: namespace
      expression: >-
        object.metadata.name

    - name: ingressSameNamespace
      expression: >-
        {
          "from": dyn([
            {
              "podSelector": dyn({})
            }
          ])
        }

    - name: egressSameNamespace
      expression: >-
        {
          "to": dyn([
            {
              "podSelector": dyn({})
            }
          ])
        }

    - name: egressCoredns
      expression: >-
        {
          "to": dyn([
            {
              "namespaceSelector": dyn({
                "matchLabels": {
                  "kubernetes.io/metadata.name": "kube-system"
                }
              }),
              "podSelector": dyn({
                "matchLabels": {
                  "app.kubernetes.io/name": "coredns"
                }
              })
            }
          ]),
          "ports": dyn([
            {
              "protocol": "UDP",
              "port": 53
            },
            {
              "protocol": "TCP",
              "port": 53
            }
          ])
        }

    - name: egressInternet
      expression: >-
        {
          "to": dyn([
            {
              "ipBlock": dyn({
                "cidr": "0.0.0.0/0",
                "except": dyn([
                  "10.0.0.0/8"
                ])
              })
            }
          ])
        }


  # Restrict communication from namespace to other namespace
  # Allow same namespace communication
  # Allow communication to CoreDNS
  # Allow communication to Internet
  generate:
    - expression: >-
        generator.Apply(variables.namespace,
          [
            {
              "kind": dyn("NetworkPolicy"),
              "apiVersion": dyn("networking.k8s.io/v1"),
              "metadata": dyn({
                "name": "default-deny",
              }),
              "spec": dyn({
                "podSelector": dyn({}),
                "policyTypes": dyn(["Ingress", "Egress"]),
                "ingress": dyn([
                  variables.ingressSameNamespace
                ]),
                "egress": dyn([
                  variables.egressSameNamespace,
                  variables.egressCoredns,
                  variables.egressInternet
                ])
              })
            }
          ]
        )



