# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.5-standalone-strict/persistentvolumeclaim-v1.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-dns-data
spec:
  storageClassName: proxmox-csi-xfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
