# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - external-secrets.io/finalizers
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        client_id: "{{ .clientId }}"
        client_secret: "{{ .clientSecret }}"
  data:
    - remoteRef:
        key: /home/tailscale/oauth/clientId
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: clientId
    - remoteRef:
        key: /home/tailscale/oauth/clientSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      secretKey: clientSecret
