---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Kube-apiserver
  become: true
  when: _mode == "systemd"
  ansible.builtin.systemd:
    name: kube-apiserver
    state: restarted
