---
# Ansible connection
ansible_user: gitea

# PostgreSQL
postgresql_project_src: "{{ ansible_facts['env']['HOME'] }}/postgres"
postgresql_data_path: "{{ ansible_facts['env']['HOME'] }}/postgres_data"

# Gitea
gitea_project_src: "{{ ansible_facts['env']['HOME'] }}/gitea"
gitea_data_path: "{{ ansible_facts['env']['HOME'] }}/gitea_data"
gitea_postgres_database: giteadb
gitea_postgres_host: localhost
gitea_postgres_port: 5432
gitea_create_admin_user: true
gitea_create_database: true

# Gitea runner
gitea_runner_project_src: "{{ ansible_facts['env']['HOME'] }}/gitea-runner"
gitea_runner_data_path: "{{ ansible_facts['env']['HOME'] }}/gitea_runner_data"
gitea_runner_gitea_url: http://gitea:3000
gitea_runner_name: infra
gitea_runner_labels: infra:docker://docker.gitea.com/runner-image:ubuntu-latest

# Nginx
nginx_profile: gitea
nginx_sites_enabled:
  - gitea.local.conf

# Tailscale
tailscale_hostname: gitea
