---
# Write kubeconfig
- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.kube"
    state: directory
    mode: "0700"

- name: Write Kubeconfig
  ansible.builtin.template:
    src: config.yaml.jinja
    dest: "{{ ansible_facts['env']['HOME'] }}/.kube/config"
    mode: "0600"

