---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-debian
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Download Kubernetes GPG key
  become: true
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ _kubernetes_minor_version }}/deb/Release.key"
    dest: "/etc/apt/keyrings/kubernetes-{{ _kubernetes_minor_version }}.asc"
    mode: "0644"

- name: Dearmor Kubernetes GPG key
  become: true
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-{{ _kubernetes_minor_version }}.gpg /etc/apt/keyrings/kubernetes-{{ _kubernetes_minor_version }}.asc"
    creates: "/etc/apt/keyrings/kubernetes-{{ _kubernetes_minor_version }}.gpg"

- name: Add Kubernetes repository
  become: true
  notify: Update apt cache
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: "https://pkgs.k8s.io/core:/stable:/v{{ _kubernetes_minor_version }}/deb"
    suites: /
    signed_by: "/etc/apt/keyrings/kubernetes-{{ _kubernetes_minor_version }}.gpg"
    state: present
    enabled: true

- name: Flush handler
  ansible.builtin.meta: flush_handlers

- name: Install Kubectl
  become: true
  ansible.builtin.apt:
    name: kubectl
    state: present
