---
- name: Preflight
  ansible.builtin.import_tasks: preflight.yaml

- name: Install
  ansible.builtin.include_tasks:
    file: "install/{{ ansible_facts['os_family'] | lower }}.yaml"

- name: Configure PKI
  ansible.builtin.import_tasks: pki.yaml

- name: Configure
  ansible.builtin.import_tasks: configure.yaml
