---
- name: Generate Kubectl key
  become: true
  register: _kubectl_key
  community.crypto.openssl_privatekey_pipe:
    size: 2048

- name: Generate CSR for Kubectl
  become: true
  register: _kubectl_csr
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ _kubectl_key.privatekey }}"
    common_name: "kubernetes-admin"
    organization_name: "system:masters"

- name: Sign Kubectl certificate
  become: true
  register: _kubectl_cert
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ _kubectl_csr.csr }}"
    provider: ownca
    ownca_content: "{{ kubectl_ca_cert_content }}"
    ownca_privatekey_content: "{{ kubectl_ca_key_content }}"
    # ownca_not_after: "{{ kubectl_not_after | default(omit) }}"
