# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-proxmox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-proxmox
  project: default
  sources:
    - repoURL: https://gitea.u74n.internal/utan/home.git
      targetRevision: main
      ref: src

    - repoURL: https://sergelogvinov.github.io/proxmox-csi-plugin
      targetRevision: main
      chart: csi-proxmox
      helm:
        valueFiles:
          - $src/k8s/platform/storage/csi-proxmox/values.yaml

    - repoURL: https://gitea.u74n.internal/utan/home.git
      targetRevision: main
      path: k8s/platform/storage/csi-proxmox

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=True
      - ServerSideApply=True
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
