---
- name: Check if join command is generated
  ansible.builtin.assert:
    that: join_command.stdout != ""
    fail_msg: "Join command is not generated. Please check the control plane node for any issues."

- name: Join the cluster (Control Plane)
  when: join_command.stdout != "" and 'control_plane' in group_names
  become: true
  ansible.builtin.command:
    cmd: >
      {{ join_command.stdout }}
      --control-plane
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Join the cluster (Worker Node)
  when: join_command.stdout != "" and 'worker' in group_names
  become: true
  ansible.builtin.command:
    cmd: "{{ join_command.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
