---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-auth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBG23AksWwxmoFOtiqqhVxRWdXWzKltqn/DfqRMV1K+zqs41zvuqU7zmm3LFa9iAl4BYU//Zf7nZaZFXz6uqox5rs0tf1S0XkmKoo+RZ8R0wV7okquOSKJRio8jiMYrkbITxwJ+fJ1fbYAhNsgFL6XthR5Sg7gahePKwIRi9c/dHjqgm3kBAAF4bAuHSngLb29MO+UpcbjAhE71AdfRii5wrBo3BLhoHdFH3Skid3AIQLDsHV9HmWRDDaH6TIfGTe9fNgmjM4OkE2Qy31vMg3Cadiv/gsuXrxHJPx4+AyB1IQH+ufybnbtYEi+E1UJ+IK+MsmEhTT+AVBhAKGNIDlqqXsSrnHbeR08bJOHWjOOibIKqomckzPOVWf11lNGcOe8KrCuhb5+oCzQaogUCA0dXMDh9mjarTBNVMbstscLdZu8EvbKV0MbCa2vYE4j8tMoRfM+ivEYlt+YJGPeIoEcdm1sRQmL7L8r/WQyNLqM1yAQiGwBwm7I/vZoDng2k62GJfZ6Ki3OxuWdjsY1O/blOQgRdq5cIWliWx2OwDVDUQZd3FWwYGlwt2luarbqh1MwKNR9V+RxPt8CU6szfdW0d+HS8f2SmsMKIcfL8i2gC7Fzx2IihqXWu9FLE9gteAMjPgq8QwYRt8rvw9WB/2ru1XkuK6MVst0tI3J1Mi6jQLLNeeuVX8wxkhY8fT0g03bdpSqCiDmqKgssZaCBX9tBYaA==
    client_secret: AgBYOJoOCT/6jXjVet4iMwIyeFU1f+ah9yUOn8HJaY5K7voqhHVgeX7Fd27W6MWe/XipLZdVjN5lkUX7DqguvEwjurNiCsuHVQrauvnp3GWHl5nFo2GJ+GWSKM0Vk81a4HJE8w9iKQKE+0ugG7hKEcxxJEYxpr7nIOleKPDMR0hM8U2DhVtFuR4tDqkQbeT1yFs5X/eA9Gl1JKaWJFA1mTIaYz2Bo6IH1NU1FVdcnMKzWA1lqUN9UjB7XpA1PSEjZeEWC6qvd0HrhpiLmxlhYOfqkezfY0z4PTBmSeZJA2Y7xjUFHoRzx2F9uMAn3aRcLCgtGudk1tEv2nSaHK8fBQBPNjXm+ihEhQM49iAp/i9vSUucmtBlYIyB0BIqmsWM9+Ds0iekd75/OnG1LNSGjESXhaOTz84NifVf/utRVL4Zc+whDsddsbwSnqZkk83aKqvROs+i3mULLFsUoKQsEKADbYIqlbQdTAwzMOorq14Noz7F/r8mPZDL6vJW+h857EmYFt8Njv2zo43K45gOqDnUf4wp/deSURGb+Md8xg/bV+fe69ECooUG8VAKX/N2S3ZfBacnKB19+4wlEDe9Glb3duLo4u8ZvdN+5lS2saH1aBlWe1ZVwnX9u2l5lJp7F7M8pEK8NwgPh7nAGgaFaSX3uhsJi98xGb1xiv+wpwfgz4NpMfc9cKvv53mnoMeRdTlfUdjXo5pCkmkniNDlX5vP4fCuMSwDSbCrJNwNrrDyT1hv61GGIq3L7mHbnLTvER/9K3wgXH9ABmksHbtU3jo=
  template:
    metadata:
      name: operator-auth
      namespace: tailscale
    type: Opaque
