---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgDSEZ0+r8iu3o/goQe5OHwIlgKBQQFifRN/TZMOY7zwoHVSegv5ExEmsoJochxU08u+7SYC65bqrh3gvWwVaa0KV+7XLhSBEqRpY8euNduz6g4fr1n1l5oF0F+FW2yBvI6XbsvhMhHJxNOijPylshVHYDcjtW7alJJ9aezic1SLXy8pACzUQ4n+JpML/t8jacU0kjgV/0TQVU1f72JVZPNDUVvfyvhizVxBEbKMVXy9DWvv+5OaMgJJlmn1HB33qk6CPH/0/GUjkpzU22PDwiHfDY1ixura9aY0hv+O03zzguQ5LSjfh0dfWeGU+LmmV+37Mw1JGm0GQMCPVne/UrpmGt35zIJBuuv3oI6toVDtCWSZYi1BJx6lAsTKg1/QaAlAWhoIYSF4HCjqcgibexGF0bBjD56iYZTh/fYb+48vtR+Jgn4uzj6F6tbrdb8Pl0fR9gU53lOHr1aXglJH7hVhFO4qBCh4gGs9aVjpRdC7qPvg+DIpupLktV5XGqA+spjNsscxHBYmq55E/BPpPbhALk3WJWeSLpDuFHQfhSzCYVE1ylNfSiIENXV9P5WtjecYvrt2LJz43FHbu6bx0qDYMVXIgOVphrrglTVJcrz+FtD0bIhZJFaFrUIRu6k3UkFb/KAReD1rlgk93+CRMS7a34Y9BO8xQaBt/yefm/U458Az77mhG/5BLrdua57hHin7bGowNhOKLJ1WVQ/UIdSWDw==
    client_secret: AgCk951cEscLQYw7HcVXZo9S43vYTz5hbzFxi8jbczjqL923ojIOwgO7OmRzv0OUJoIGeqebgrkJfDN0IVEfxjrrV4AfJ6oFspU9K9sENAhP+/kIqdXyFRyWdKHA/zMobzmSjxJ6GwbyiEhgLH+4lLil/+zWR0HD44Pco9ZhBr6if6bLGJ/Zv3miJEuFFMeWKMF8yA3DusUOBVpYUyFAU6ktVkpSCtYBsSwNpYPP3P/lBEa3RVRkOwq4XhK1IbVJJpEh0qZm1IGWWqfO0enzJti3DijbSNAQrkDyXIvVUQ2xQqwDcFSlHFBzSbvy3qNpMsFfeQvT+wyFi1E2tkaZr1CuDP+JxwmBp06aQ3Qh2XmBl7U+tZs1EeoCJUVDTQmOOQnANDBMl17IYQ/LmWdMvuXOqNpBEB2qOjN2c9kyiUrUp7jn3j2IhpZPuZ6ytBJ3sTwhv1zWisAke+9l7JxCdLPYPJbGcYAh+jMAp7u3fuD68yDpbJ8975ALd70ffcsliqpTwvBb+KdjvfCawdTHQSporeZxA76fMtnsrtpf2wjsIByJYxC7qaSyR3Hz0kVnj0wLWd1KVE2RrJOfb2NQYgAjFWwXUxvMBWjest59Z37BTP0fa8ODVu+1l1hxLsYPsoxm1623TU2pgzi9M0rNhKyz6jQhzEZSGrqq32f883m5gmtscl2stECQsb9RJEPXK7YF0k8t4StHQO+vi1RGxbvLy9YQwAg0fqLfh2ghxBTY6mhKkHqbbhewHb9yLssQE6wex5Mi/TK5RxS9jCqdyrc=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
