---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgDBRzJc5xbzJKsn1xXMCjOr/5P9Gd4rkEojsD3xELtOQ4K18H8T9htuXGKisGmA/C6GfISHBR/nCwDQw6JBS4+B7M55VzbtdBAg8BGmikspMQo0il+OnbTl9t8oGmbt+74bYbZsSCzuIAIj+1CVD0JawTcSFyFNYxBgDqPV1tWfnApHmbhPrib6XRAKUtZer5r2c340B20D/7qUZWcXLhme6DV8l5PadAAnSjth3rRzrNj6H0I/YPAEckwbHwKsEpVVr//LpGqW2Ybq49Z/BxtyWeWgclcf5RW7db0a7riMyUCd/2QPo0T9jWoSU2kRyTJ+mqRo5d3wWgxC2A4HRUeVHpP11QF/Vy1O8LWpjiPes3sRQYMsYSNTgXL0JPmqu50CcHBboKzDcPHsZggLCiUfcVRHXPhqRJHOJcqcKHXy8Hs40iEkEu+BQgsnNxjnWtS5KuNLDX8A3s0y50Drw42T5XUINm90D4WQuPSx19/iWsHQJnZjmTzYpahlPS3NHYZRKG9YwV/UH9K05+4RR3+3otu5pfMWq7thN3HV0WUqRoNAZYn/IkqGj2v6l1AxwLFqybgc3eozfcELaStgT9b6u8FgPXrDZlHPLse1NHXMWZZ3a6dUL6kfA+WAl927LkmpymwTyvcUfJ0G3/4roi/W2GB7IPVOWDkaBnAeP1Lixv0hiqqFxx4xB0NTmdu7fKgMImeQnHOpZUnfKG+4C7w1Og==
    client_secret: AgCjRJh6nLhfn56xE4XK51jsWk0wEIjjDrIsqXyMURTkWYJhW4alWrDjdIXCKtYYyTxDIIF6gpvytXdv2wWSJVqd39CBY9wpXiG4pD5WCblkugjL4SZXwonvESP+CV/IE684CRMfMHPHYJwxrXMUx5/ewoATUQC8WetbdWbfM0zQz8zjHRXVHKSQKFx+2sFR7UULq2oamUdPdK25tGyu/48oaOAZJ6A7wdfhyuoXRL+GM3160na94V7NV6dY/jSrDWrrtVaZGqRLnjDtpFVfjcGJupoBPcUB1nPXQ13MOvOJ1ysH2Tx8X3w+2zXXhWSmS5edOK+QhRquQui0cX+S+VgZIue6khrj6LDNeANg0zh9+pIuFLhfJqxDQtTlGWHNjdKLRe/EpihX8GWhgjw0DVFSTbqzHsxrV1OD27KSVX8jbXS/zBX5OTrTdnLKawRsSRvu+mRXP+VmxsnrMeawX59KZ1az1VGxeu2ZuDMglIW3iRtw/3qqt8iah/D5Hwg02bV8JRSP6BY+Mme2nZ6rUKCj5Htn/k4OypLufRGeFECdk4yscpN83C30ucr8B9EJsNNBGSNQFETx7kviKTf9WpsbYxfs3TyQX+sxMwj7Tr2WEedR337Cm5HE9DSIX3namAW4Evz1iRWA+5ZNVjFI6RoD9Iw7SFoCF8TaRqedvrSVYFAfjmQajBQqPt80yLeQyEoGiT2k8WW4opHNvOGTTNFKl4QO+vbpTy9UoPHIjD3cBciP/XcDpBKcIMAWfd+ytYuHaUs8YN05Bq3X5D1tSRU=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
