---
- name: Install dependencies
  become: true
  ansible.builtin.dnf:
    name: "{{ _kubectl_dependencies_redhat }}"
    state: present

- name: Add Kubernetes repository
  become: true
  notify: Update dnf cache
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes - $basearch
    baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ _kubectl_minor_version }}/rpm"
    enabled: true
    gpgcheck: true
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v{{ _kubectl_minor_version }}/rpm/repodata/repomd.xml.key"

- name: Flush handler
  ansible.builtin.meta: flush_handlers

- name: Install Kubectl
  become: true
  ansible.builtin.dnf:
    name: kubectl
    state: present
