---
_kube_scheduler_dependencies:
  - "{{ 'python3-cryptography' if ansible_facts['os_family'] != 'ArchLinux' else 'python-cryptography' }}"

_kube_scheduler_flags: |
  --bind-address=0.0.0.0
  --leader-elect=true
  --kubeconfig=/etc/kubernetes/scheduler.conf
  --v=2

_kube_scheduler_systemd_flags: "{{ _kube_scheduler_flags.splitlines() | join(' ') }}"
_kube_scheduler_static_pod_flags: |-
  {% for flag in _kube_scheduler_flags.splitlines() %}
  - {{ flag }}
  {% endfor %}

_kube_scheduler_is_installation_dir_blank: "{{ kube_scheduler_installation_dir is not truthy }}"
_kube_scheduler_is_static_pod_dir_blank: "{{ kube_scheduler_static_pod_dir is not truthy }}"
