---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Kube-controller-manager
  become: true
  when: _mode == "systemd"
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: restarted
