---
argument_specs:
  main:
    description: Install and configure Tailscale
    short_description: Install and configure Tailscale
    author:
      - U74n
    options:
      tailscale_auth_key: 
        type: str 
        description:
          - "Tailscale authentication key to join the Tailnet"
          - "You can generate an auth key from the Tailscale admin console"
        required: true

      tailscale_hostname: 
        type: str 
        description:
          - "Hostname to use for the Tailscale node"
          - "Default: if not provided, It will use the Ansible fact 'hostname'"
        required: false 
        default: "{{ ansible_facts['hostname'] }}"
