---
- name: Preflight
  ansible.builtin.import_tasks: preflight.yaml

- name: Install
  ansible.builtin.import_tasks: install.yaml

- name: Configure
  ansible.builtin.import_tasks: configure.yaml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Gitea is running
  community.docker.docker_compose_v2:
    project_src: "{{ gitea_project_src }}"
    wait: true
    wait_timeout: 60
    state: present

- name: Ensure Gitea admin user
  when:
    - gitea_create_admin_user
    - gitea_admin_user not in (_gitea_admin_user_check.stdout | default(''))
  failed_when: false
  community.docker.docker_container_exec:
    container: gitea_server
    argv:
      - "gitea"
      - "--work-path"
      - "/var/lib/gitea"
      - "admin"
      - "user"
      - "create"
      - "--username"
      - "{{ gitea_admin_user }}"
      - "--password"
      - "{{ gitea_admin_password }}"
      - "--email"
      - "{{ gitea_admin_email }}"
      - "--admin"
