---
- name: Ensure Etcd directories
  become: true
  loop_control:
    loop_var: etcd_dir
  loop:
    - "{{ etcd_installation_dir }}"                                             # Installation directory
    - "{{ etcd_pki_dir }}"                                                      # PKI directory
    - "{{ kubernetes_static_pod_dir if etcd_mode == 'staticpod' else omit }}"   # Static pod directory
  ansible.builtin.file:
    path: "{{ etcd_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Etcd binaries
  become: true
  ansible.builtin.get_url:
    url: "{{ etcd_download_url }}/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "{{ etcd_installation_dir }}/etcd-v{{ etcd_version }}.tar.gz"
    mode: "0755"

- name: Extract Etcd binaries
  become: true
  ansible.builtin.unarchive:
    src: "{{ etcd_installation_dir }}/etcd-v{{ etcd_version }}.tar.gz"
    dest: "{{ etcd_installation_dir }}"
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Symlink Etcd binaries
  become: true
  loop:
    - "{{ 'etcd' if etcd_mode == 'systemd' else omit }}"
    - etcdctl
  ansible.builtin.file:
    src: "{{ etcd_installation_dir }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: true
