---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _etcd_dependencies }}"
    state: present

# Set Etcd CA key, if not found create one at the first control plane
- name: Set Etcd CA key
  when: etcd_ca_key_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_key.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: /etc/etcd/pki/ca.key
    variable: etcd_ca_key_content

# Set Etcd CA certificate, if not found create on at the first control plane
- name: Set Etcd CA certificate
  when: etcd_ca_cert_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_cert.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: /etc/etcd/pki/ca.crt
    variable: etcd_ca_cert_content
    ca_key_content: "{{ etcd_ca_key_content }}"
    ca_common_name: Etcd CA

# Gather service facts
- name: Gather service facts
  become: true
  ansible.builtin.service_facts:

# Stat files for config lock mechanism
- name: Stat systemd service
  become: true
  register: _etcd_systemd_file
  ansible.builtin.stat:
    path: /etc/systemd/system/etcd.service

- name: Stat static pod manifest
  become: true
  register: _etcd_static_pod_file
  ansible.builtin.stat:
    path: "{{ etcd_static_pod_dir }}/etcd.yaml"

- name: Stat WAL directory
  become: true
  register: _etcd_wal_data
  ansible.builtin.stat:
    path: /var/lib/etcd/member/wal

# Ensure etcd_installation_dir is correctly set
- name: Assert etcd_installation_dir is correctly set
  when: _etcd_is_etcd_installation_dir_blank
  ansible.builtin.fail:
    msg: "etcd_installation_dir is required."

# Ensure etcd_static_pod_dir is correctly set
- name: Assert etcd_static_pod_dir is correctly set
  when:
    - etcd_mode == "staticpod"
    - _etcd_is_etcd_static_pod_dir_blank
  ansible.builtin.fail:
    msg: "etcd_static_pod is required when deployment mode is staticpod."
