---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: "http://192.168.1.20:3000/utan/home.git"
      targetRevision: main
      path: k8s/gitops/
      directory:
        recurse: true
    # CRD
    - repoURL: "https://github.com/kubernetes-sigs/gateway-api"
      targetRevision: release-1.4
      path: config/crd/standard

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
