---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ThatU74n/home.git
    targetRevision: main
    path: k8s/deployments/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
