---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ThatU74n/home.git
    targetRevision: vaultwarden
    path: k8s/deployments/vaultwarden
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
