redis:
  enabled: false

postgresql:
  enabled: false
  useExistingPostgresSecret:
    enabled: true
    existingConnectionStringSecret:
      name: "infisical-db-connection-string"
      key: "uri"

ingress:
  enabled: false
  nginx:
    enabled: false

infisical:
  enabled: true
  fullnameOverride: infisical
  serviceAccount:
    create: false
  replicaCount: 1
  service:
    type: ClusterIP
  extraEnv:
    - name: REDIS_URL
      value: redis://valkey.valkey.svc.cluster.local:6379
    - name: ALLOW_INTERNAL_IP_CONNECTIONS
      value: true
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi

