---
kind: Service
apiVersion: v1
metadata:
  name: chartdb-service
  namespace: chartdb
spec:
  selector:
    app: chartdb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      appProtocol: http
