---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure package
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Check K3s
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_stat

- name: Install K3s if not present
  when: not k3s_stat.stat.exists
  ansible.builtin.import_tasks: install.yml
# - name: Uninstall K3s if present
#   when: k3s_stat.stat.exists
#   ansible.builtin.import_tasks: uninstall.yml
