---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tailscale
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.94.2
      helm:
        valueFiles:
          - $tailscale/values.yaml
    - repoURL: https://github.com/ThatU74n/home.git
      targetRevision: main
      path: k8s/helm/tailscale
      ref: tailscale
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
