---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
spec:
   managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: gitea
        superuser: false
        login: true
        passwordSecret:
          name: gitea-db-cred

      - connectionLimit: -1
        ensure: present
        inherit: true
        name: grafana
        superuser: false
        login: true
        passwordSecret:
          name: grafana-db-cred

      - connectionLimit: -1
        ensure: present
        inherit: true
        name: infisical
        superuser: false
        login: true
        passwordSecret:
          name: infisical-db-cred

