---
kube_apiserver_version: 1.35.4
kube_apiserver_mode: staticpod
kube_apiserver_installation_dir: /usr/local/kubernetes
kube_apiserver_static_pod_dir: /etc/kubernetes/manifests
kube_apiserver_pki_dir: /etc/kubernetes/pki
kube_apiserver_etcd_pki_dir: /etc/etcd/pki
kube_service_cluster_ip_range: 10.32.0.0/24
kube_apiserver_ca_cert_content:
kube_apiserver_ca_key_content:
kube_apiserver_etcd_ca_cert_content:
kube_apiserver_etcd_ca_key_content:
kube_apiserver_storage_backend: etcd3
