---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistent.annotation }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- if .Values.persistent.labels }}
    {{- toYaml .Values.persistent.labels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- toYaml .Values.persistent.accessModes | nindent 4 }}
  volumeMode: {{ .Values.persistent.volumeMode }}
  storageClassName: {{ .Values.persistent.storageClassName }}
  resources:
    {{- toYaml .Values.persistent.resources | nindent 4 }}
  {{- with .Values.persistent.selector }}
  selector:
    {{- toYaml .Values.persistent.selector | nindent 4 }}
  {{- end}}
    
