---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }} 
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
