---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-grafana"
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers: 
        - name: grafana 
          image: "{{ .Values.grafana.repository }}:{{ .Values.grafana.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-grafana-admin-password"
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config
          configMap:
            name: "{{ .Release.Name }}-grafana-datasource-config"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-grafana"
spec:
  type: ClusterIP
  selector:
    app: grafana 
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: "{{ .Release.Name }}-grafana-datasource-config"
data:
  datasource.yaml: |-
    apiVersion: 1 

    datasources:
      - name: Prometheus 
        type: prometheus 
        access: proxy 
        url: http://{{ .Release.Name }}-prometheus:9090
        isDefault: true
