---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-sonarqube"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-sonarqube"
    spec:
      containers:
        - name: sonarqube 
          image: "{{ .Values.sonarqube.repository }}:{{ .Values.sonarqube.tag }}"
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://postgresql-pooler:5432/sonarqube"
            - name: SONARQUBE_JDBC_USERNAME
              value: sonarqube
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgresql-cluster-{{ .Values.database.user }}"
                  key: password
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1 
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-sonarqube"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
# ---
# apiVersion: k8s.gateway.api/v1beta1
# kind: HTTPRoute
# metadata:
#   name: "{{ .Release.Name }}-http-route"
# spec:
#   parentRefs:
#     - name: "{{ .Release.Name }}-gateway"

