---
- name: Copy configuration template
  become: true
  when: kube_apiserver_mode == "systemd"
  ansible.builtin.template:
    src: kube-apiserver.service.jinja
    dest: /etc/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Kube-apiserver

  # Encryption configure is a one time action because
  # the secret key inside the configuration is set to be random every run.
  # If you want to change encryption configuration, just delete the file.
- name: Copy encryption configuration
  become: true
  block:
    - name: Stat encryption configuration file exists
      register: _kube_apiserver_encryption_config_stat
      ansible.builtin.stat:
        path: /etc/kubernetes/encryption-config.yaml

    - name: Copy configuration
      when: not _kube_apiserver_encryption_config_stat.stat.exists
      ansible.builtin.template:
        src: encryption-config.yaml.jinja
        dest: "/etc/kubernetes/encryption-config.yaml"
        owner: root
        group: root
        mode: "0600"
