---
- name: Ensure Kubernetes directory
  become: true
  loop_control:
    loop_var: kubernetes_directory
  loop:
    - "{{ kube_apiserver_installation_dir if kube_apiserver_mode == 'systemd' else omit }}"
    - "{{ kube_apiserver_pki_dir }}"
    - "{{ kube_apiserver_static_pod_dir if kube_apiserver_mode == 'staticpod' else omit }}"
  ansible.builtin.file:
    path: "{{ kubernetes_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Kube-apiserver binary
  become: true
  when: kube_apiserver_mode == "systemd"
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/v{{ kube_apiserver_version }}/bin/linux/amd64/kube-apiserver"
    dest: "{{ kube_apiserver_installation_dir }}/kube-apiserver-{{ kube_apiserver_version }}"
    checksum: "sha256:{{ kube_apiserver_checksum }}"
    owner: root
    group: root
    mode: "0755"

- name: Symlink Kube-apiserver binary
  become: true
  when: kube_apiserver_mode == "systemd"
  ansible.builtin.file:
    src: "{{ kube_apiserver_installation_dir }}/kube-apiserver-{{ kube_apiserver_version }}"
    dest: /usr/local/bin/kube-apiserver
    state: link
  notify:
    - Restart Kube-apiserver
