---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _kube_apiserver_dependencies }}"
    state: present

# Set Kubernetes CA key, if not found create one at the first control plane
- name: Set Kubernetes CA key
  when: kube_apiserver_ca_key_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_key.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: "{{ kube_apiserver_pki_dir }}/ca.key"
    variable: kube_apiserver_ca_key_content

# Set Kubernetes CA certificate, if not found create one at the first control plane
- name: Set Kubernetes CA certificate
  when: kube_apiserver_ca_cert_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_cert.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: "{{ kube_apiserver_pki_dir }}/ca.crt"
    variable: kube_apiserver_ca_cert_content
    ca_key_content: "{{ kube_apiserver_ca_key_content }}"
    ca_common_name: Kubernetes CA

# Set Etcd CA key, if not found create one at the first control plane
- name: Set Etcd CA key
  when: kube_apiserver_etcd_ca_key_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_key.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: "{{ kube_apiserver_etcd_pki_dir }}/ca.key"
    variable: kube_apiserver_etcd_ca_key_content

# Set Etcd CA certificate, if not found create one at the first control plane
- name: Set Etcd CA certificate
  when: kube_apiserver_etcd_ca_cert_content is not truthy
  run_once: true
  ansible.builtin.include_tasks:
    file: util/slurp_or_create_ca_cert.yaml
  vars:
    task_delegate_to: "{{ groups['control_plane'] | sort | first }}"
    path: "{{ kube_apiserver_etcd_pki_dir }}/ca.crt"
    variable: kube_apiserver_etcd_ca_cert_content
    ca_key_content: "{{ kube_apiserver_etcd_ca_key_content }}"
    ca_common_name: Etcd CA

# Fetch Kube API server checksum
- name: Fetch Kube API server checksum
  when:
    - kube_apiserver_mode == "systemd"
    - not kube_apiserver_checksum
  block:
    - name: Get Kube API server checksum
      changed_when: false
      register: _kube_apiserver_checksum_result
      ansible.builtin.uri:
        url: "https://dl.k8s.io/v{{ kube_apiserver_version }}/bin/linux/amd64/kube-apiserver.sha256"
        return_content: true

    - name: Set Kube API server checksum fact
      ansible.builtin.set_fact:
        kube_apiserver_checksum: "{{ _kube_apiserver_checksum_result.content }}"

# Gather service facts
- name: Gather service facts
  become: true
  ansible.builtin.service_facts:

# Ensure kube_apiserver_installation_dir is correctly set
- name: Assert kube_apiserver_installation_dir is correctly set
  when: _kube_apiserver_is_installation_dir_blank
  ansible.builtin.fail:
    msg: "kube_apiserver_installation_dir is required."

# Ensure kube_apiserver_static_pod_dir is correctly set
- name: Assert kube_apiserver_static_pod_dir is correctly set
  when:
    - kube_apiserver_mode == 'staticpod'
    - _kube_apiserver_is_static_pod_dir_blank
  ansible.builtin.fail:
    msg: "kube_apiserver_static_pod_dir is required when deployment mode is staticpod."
