---
galaxy_info:
  author: U74n
  description: Install and configure kubelet
  min_ansible_version: 2.20
  platforms:
    - name: Debian
      versions:
        - 13       - Trixie
        - 12       - Bookworm

    - name: CentOS
      versions:
        - stream 10 - Coughlan

    - name: Fedora
      versions:
        - 43
        - 42
