namespace: "home"
readme: "../doc/README.md"
name: "configuration"
version: "1.0.0"
authors:
  - "U74n utan.dev2358@gmail.com>"
description: "Homelab configuration"
# Dependencies on other collections (optional)
dependencies:
  "community.general": ">=12.5.0"
  "community.docker": ">=5.1.0"
  "community.hashi_vault": ">=5.0.0"
  "community.proxmox": ">=1.6.0"
  "community.postgresql": ">=4.2.0"
  "kubernetes.core": ">=6.3.0"

repository: "https://github.com/ThatU74n/home"
