---
- name: Configure Control Plane Nodes
  hosts: control_plane
  tasks:
    - name: Configure K3s Control Plane
      ansible.builtin.import_role:
        name: k3s_control_plane

- name: Configure Worker Nodes
  hosts: worker
  tasks:
    - name: Configure K3s Worker Node
      ansible.builtin.import_role:
        name: k3s_worker
