---
gitea_tag:
gitea_project_src: "{{ ansible_facts['env']['HOME'] }}/gitea"
gitea_data_path:
gitea_create_admin_user: true
gitea_admin_user: gitea
gitea_admin_password:
gitea_admin_email: admin@admin.com
gitea_create_database: true
gitea_postgres_host: localhost
gitea_postgres_port: 5432
gitea_postgres_super_user: postgres
gitea_postgres_super_password:
gitea_postgres_user: gitea
gitea_postgres_password:
gitea_postgres_database: giteadb
