---
- name: Check
  ansible.builtin.import_tasks: check.yaml
- name: Install
  ansible.builtin.import_tasks: install.yaml

- name: Join Tailnet
  become: true
  ansible.builtin.command:
    cmd: tailscale up --authkey {{ tailscale_auth_key }} --hostname {{ tailscale_hostname | default(ansible_facts['hostname']) }}
  args:
    creates: /var/lib/tailscale/tailscaled.state
