all:
  children:
    control_plane:
      hosts:
        etcd:
          ansible_host: 13.215.153.144
          ansible_user: admin
        #
        # control-plane-1:
        #   ansible_host:
        #   ansible_user:
        #
        # control-plae-2:
        #   ansible_host:
        #   ansible_user:
