---
all:
  children:
    proxmox:

    proxmox_backup_server:
      hosts:
        vostro:
          ansible_host: 192.168.10.20
          ansible_user: u74n
          ansible_private_key_file: ~/.ssh/id_ed25519

    firewall:


    ca:
      hosts:
        stepca:
          ansible_user: root

    gitea:
      hosts:
        vostro:


    control_plane:

    worker:

    local:
      hosts:
        localhost:
          ansible_connection: local
