---
global:
  storageClass: proxmox-storage-zfs
  replicaCount: 1

strategy:
  type: Recreate

service:
  http:
    type: ClusterIP
  ssh:
    annotations:
      tailscale.com/hostname: "gitea"
    type: LoadBalancer
    loadBalancerClass: tailscale

ingress:
  enabled: false

gatewayAPI:
  enabled: true
  core:
    httpRoute:
      enabled: true
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: cilium-gw
          namespace: gateway
          sectionName: https
      hostnames:
        - gitea.k8s.u74n.internal

deployment:
  labels:
    internal-ca: "true"
  resources:
    request:
      cpu: 100m
      memory: 128Mi
    limit:
      cpu: 500m
      memory: 512Mi

persistence:
  enabled: true
  size: 10Gi
  storageClass: proxmox-csi-xfs

valkey:
  enabled: false
valkey-cluster:
  enabled: false
postgresql-ha:
  enabled: false
postgresql:
  enabled: false


gitea:
  admin:
    existingSecret: gitea-admin-cred
    passwordMode: keepUpdated
  config:
    git.config: {}
    database:
      DB_TYPE: postgres
      HOST: postgresql-cluster-rw.cnpg.svc.cluster.local:5432
      NAME: giteadb
      USER: gitea
      SSL_MODE: disable
    server:
      ROOT_URL: https://gitea.k8s.u74n.internal # gateway route missmatch the default gen, gitea behind proxy
    webhook:
      ALLOWED_HOST_LIST: "pac.k8s.u74n.internal"
  additionalConfigFromEnvs:
    - name: GITEA__database__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea-db-cred
          key: password

