---
_kubectl_dependencies_debian:
  - python3-debian
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg

_kubectl_dependencies_redhat:
  - python3
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg

_kubectl_minor_version: "{{ kubectl_version.split('.')[0:2] | join('.') }}"

_kubectl_first_control_plane_host: "{{ groups['control_plane'] | sort | first }}"
